on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/npm@v2
        with:
          args: install
      - name: npm test
        uses: actions/npm@v2
        with:
          args: run test
      - name: npm lint
        uses: actions/npm@v2
        with:
          args: run lint
      - name: docker build
        uses: actions/docker/cli@v2
        with:
          args: build -t pt6000/github-action-example-node .
      - name: docker login
        uses: actions/docker/login@v2
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@v2
        with:
          args: push pt6000/github-action-example-node
